version: "3.7"

services:

  app:
    image: balancetracker
    ports:
      - 4000:5000
  
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: clients